In [4]:
from bs4 import BeautifulSoup
import requests
import selenium
import pandas as pd
import numpy as np
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')

# Q1

Write a python program which searches all the product under a particular product from www.amazon.in. The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars.

In [82]:
amazon=webdriver.Chrome()
time.sleep(5)
amazon.get('http://www.amazon.in')
amazon.maximize_window()

In [83]:
product=amazon.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
product.send_keys(input('Enter product name:'))
search_button=amazon.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
search_button.click()

Enter product name:football

# Q2

In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then scrape all the products available under that product name. Details to be scraped are: "Brand
Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and
“Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [84]:
urls=[]
for page in range(0,3):
    url=amazon.find_elements(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    for i in url:
        urls.append(i.get_attribute('href'))
nb=amazon.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[1]/div[1]/div/span[1]/div[1]/div[64]/div/div/span/a[2]')
nb.click()
len(urls)

204

In [75]:
brand=[]
for i in urls:
    amazon.get(i)
    time.sleep(1)
    try:
        bn=amazon.find_element(By.XPATH,'//td[@class="a-span9"]')
        brand.append(bn.text)
    except NoSuchElementException as e:
        brand.append('-')

In [52]:
brand=[]
product_name=[]
price=[]
return_exchange=[]
expected_delivery=[]
availability=[]

for i in urls:
    amazon.get(i)
    time.sleep(1)
    try:
        bn=amazon.find_element(By.XPATH,'//td[@class="a-span9"]')
        brand.append(bn.text)
    except NoSuchElementException as e:
        brand.append('-')
        
    try:
        pn=amazon.find_element(By.XPATH,'//span[@class="a-size-large product-title-word-break"]')
        product_name.append(pn.text)
    except NoSuchElementException as e:
        product_name.append('-')

    try:
        pr=amazon.find_element(By.XPATH,'//span[@class="a-price-whole"]')
        price.append(pr.text)
    except NoSuchElementException as e:
        price.append('-')
    try:
        re=amazon.find_element(By.XPATH,'//span[@class="a-size-small a-color-link a-text-normal"]')
        return_exchange.append(re.text)
    except NoSuchElementException as e:
        return_exchange.append('-')
    try:
        ed=amazon.find_element(By.XPATH,'//span[@class="a-text-bold"]')
        expected_delivery.append(ed.text)
    except NoSuchElementException as e:
        expected_delivery.append('-')
    try:
        av=amazon.find_element(By.XPATH,'//span[@class="a-size-medium a-color-success"]')
        availability.append(av.text)
    except NoSuchElementException as e:
        availability.append('-')

In [79]:
len(brand),len(product_name),len(price),len(return_exchange),len(expected_delivery),len(availability),len

(204, 204, 204, 204, 204, 204)

In [137]:
products=pd.DataFrame({'Brand':brand,'Product':product_name,'Price':price,'Return/Exchange':return_exchange,'Expected Delivery':expected_delivery,'Availability':availability,'Product URL':urls})
products.to_csv('football.csv')
football=pd.read_csv('football.csv')
football

,Brand,Product,Price,Return/Exchange,Expected Delivery,Availability,Product URL
0,Generic,SSC Black and White Football Size-5 with Air P...,380,Free Delivery,"Friday, 23 June",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,Volatility,SSC Black and White Football Size-5 with Needl...,350,Free Delivery,"Friday, 23 June",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,Generic,JTC World Cup PU Football with Air Pump Size -...,599,Free Delivery,"Friday, 23 June",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Mayor,"Varun Hand Stitched Black and White, PU Footba...",299,10 days Returnable,"Saturday, 24 June",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,Nivia,Nivia Storm Football | Rubberized Moulded | Su...,343,Free Delivery,"Tuesday, 20 June",In stock,https://www.amazon.in/Nivia-Storm-Football-Siz...
...,...,...,...,...,...,...,...
199,Cosco,"cosco Rio (Orange) Football, Size 3 (Multicolour)",420,Free Delivery,"Thursday, 22 June",-,https://www.amazon.in/cosco-Orange-Football-Si...
200,Cosco,"Cosco Hurricane Football - Size 5, White",499,Free Delivery,"Wednesday, 21 June",In stock,https://www.amazon.in/Cosco-Hurricane-Football...
201,Nivia,"Nivia Dominator 3.0 Football Size - 5(Soccer, ...","1,229",Free Delivery,"Tuesday, 20 June",In stock,https://www.amazon.in/NIVIA-Dominator-3-0-Foot...
202,Nivia,NIVIA Shining Star STITCHLESS Football Size 5 ...,898,Free Delivery,"Monday, 26 June",In stock,https://www.amazon.in/NIVIA-Shining-STITCHLESS...
203,Nivia,"Nivia 279 Torrido Pu Football, Size 5 (White/O...",989,Free Delivery,"Tuesday, 20 June",In stock,https://www.amazon.in/Nivia-Torrido-Football-W...

# Q3

Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [164]:
google=webdriver.Chrome()

google.maximize_window()

In [171]:
urls2 = []    
data = []
items= ["fruits", "cars", "Machine Learning","guitar","cakes"]
for i in items: 
    google.get('http://google.com')
    time.sleep(5)
    google_images=google.find_element(By.XPATH,'/html/body/div[1]/div[1]/div/div/div/div[1]/div/div[2]/a').click()
    search_bar=google.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea').send_keys(i)
    search_button =google.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div').submit()
    
    for _ in range(20):
        google.execute_script("window.scrollBy(0,1000)")
        
        images=google.find_elements(By.XPATH,"//img[@class='rg_i Q4LuWd']")
        
        img_url = []
        for i in images:
            source = i.get_attribute('src')
            if source is not None:
                    if(source[0:4] == 'http'):
                        img_url.append(source)
        for i in img_url[:10]:
            urls2.append(i)
                    
for i in range(len(urls)):
    if i > 50:
        break
    print("Downloading {0} of {1} images" .format(i, 50))
    response = requests.get(urls[i])
    file=open(r"D:\Nimish"+str(i)+".jpg",'wb')
    file.write(response.content)

Downloading 0 of 50 images
Downloading 1 of 50 images
Downloading 2 of 50 images
Downloading 3 of 50 images
Downloading 4 of 50 images
Downloading 5 of 50 images
Downloading 6 of 50 images
Downloading 7 of 50 images
Downloading 8 of 50 images
Downloading 9 of 50 images
Downloading 10 of 50 images
Downloading 11 of 50 images
Downloading 12 of 50 images
Downloading 13 of 50 images
Downloading 14 of 50 images
Downloading 15 of 50 images
Downloading 16 of 50 images
Downloading 17 of 50 images
Downloading 18 of 50 images
Downloading 19 of 50 images
Downloading 20 of 50 images
Downloading 21 of 50 images
Downloading 22 of 50 images
Downloading 23 of 50 images
Downloading 24 of 50 images
Downloading 25 of 50 images
Downloading 26 of 50 images
Downloading 27 of 50 images
Downloading 28 of 50 images
Downloading 29 of 50 images
Downloading 30 of 50 images
Downloading 31 of 50 images
Downloading 32 of 50 images
Downloading 33 of 50 images
Downloading 34 of 50 images
Downloading 35 of 50 images
Downloading 36 of 50 images
Downloading 37 of 50 images
Downloading 38 of 50 images
Downloading 39 of 50 images
Downloading 40 of 50 images
Downloading 41 of 50 images
Downloading 42 of 50 images
Downloading 43 of 50 images
Downloading 44 of 50 images
Downloading 45 of 50 images
Downloading 46 of 50 images
Downloading 47 of 50 images
Downloading 48 of 50 images
Downloading 49 of 50 images
Downloading 50 of 50 images

# Q4

Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”,
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [319]:
flipkart=webdriver.Chrome()
flipkart.get('http://flipkart.com')
flipkart.maximize_window()

In [321]:
search=flipkart.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')
search.send_keys(input('smartphone name:'))
search_button= flipkart.find_element(By.CLASS_NAME,'L0Z3Pu').click()

smartphone name:nord2t

In [322]:
page1_urls =[]
urls = flipkart.find_elements(By.XPATH,'//a[@class="_1fQZEK"]')
for url in urls:
    page1_urls.append(url.get_attribute("href"))

In [332]:
Brand = []
Phone_name = []
Colour = []
RAM= []
ROM = []
Primary_Camera= []
Secondary_Camera = []
Display_Size= []
Battery_Capacity = []
Price = []

In [333]:
for url in page1_urls:
    flipkart.get(url)              
    URL.append(url)                                                          
    time.sleep(2)
    read_more = flipkart.find_element(By.XPATH,'//button[@class="_2KpZ6l _1FH0tX"]')     
    read_more.click()
    
        
    
    #Scraping brand name of phone
    try:
        brand_tags = flipkart.find_element(By.XPATH,'//span[@class="B_NuCI"]')      
        Brand.append(brand_tags.text.split()[0])
    except NoSuchElementException:
        Brand.append('-')
    
    
    #Scraping phone name 
    try:
        name_tags = flipkart.find_element(By.XPATH,'//div[@class="_3k-BhJ"][1]/table/tbody/tr[3]/td[2]/ul/li')     
        Phone_name.append(name_tags.text)
    except NoSuchElementException:
        Phone_name.append('-')
         
    #Scraping RAM 
    try:
        ram_tags = flipkart.find_element(By.XPATH,'//div[@class="_3k-BhJ"][4]/table[1]/tbody/tr[2]/td[2]/ul/li')                
        RAM.append(ram_tags.text)
    except NoSuchElementException:
        RAM.append('-')
    
    
    #Scraping ROM 
    try:
        rom_tags = flipkart.find_element(By.XPATH,'//div[@class="_3k-BhJ"][4]/table[1]/tbody/tr[1]/td[2]/ul/li')        
        ROM.append(rom_tags.text)
    except NoSuchElementException:
        ROM.append('-')
        
        
    #Scraping Primary camera 
    try:                                                                                    
        pri_tags = flipkart.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div[1]/div[2]/div[7]/div/div/div[2]/ul/li[3]')
        Primary_Camera.append(pri_tags.text)
    except NoSuchElementException:
        Primary_Camera.append('-')
        
     #Scraping display size    
    try:                                                                                    
        dis = flipkart.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div[1]/div[2]/div[7]/div/div/div[2]/ul/li[2]')
        Display_Size.append(dis.text)
    except NoSuchElementException:
        Display_Size.append('-')
    
    #Scraping colour
    try:                                                                                    
        col = flipkart.find_element(By.XPATH,'//div[@class="_3k-BhJ"][1]/table/tbody/tr[4]/td[2]/ul/li')
        Colour.append(col.text)
    except NoSuchElementException:
        Colour.append('-')
        
     #Scraping battery
    try:                                                                                    
        batt = flipkart.find_element(By.XPATH,'//div[@class="_3k-BhJ"][7]/table/tbody/tr/td[2]/ul/li')
        Battery_Capacity.append(batt.text)
    except NoSuchElementException:
        Battery_Capacity.append('-')
        
    #Scraping prices
    try:                                                                                    
        prices = flipkart.find_element(By.XPATH,'//div[@class="_30jeq3 _16Jk6d"]')
        Price.append(prices.text)
    except NoSuchElementException:
        Price.append('-')

In [334]:
smartphone=pd.DataFrame({"brand_name":Brand[:24],"smartphone_name":Phone_name[:24],"product_colour":Colour[:24],"product_RAM":RAM[:24],
                         "product_ROM":ROM[:24],"Primary_Camera":Primary_Camera[:24],"Display_size":Display_Size[:24],"Battery_Capacity":Battery_Capacity[:24],"Phone_Price":Price[:24],"Product_URL":page1_urls[:24]})
smartphone.to_csv('smartphonecsv')
smartphone

,brand_name,smartphone_name,product_colour,product_RAM,product_ROM,Primary_Camera,Display_size,Battery_Capacity,Phone_Price,Product_URL
0,OnePlus,Nord 2T 5G,Jade Fog,8 GB,128 GB,50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh,"₹28,025",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
1,OnePlus,Nord 2T 5G,Gray Shadow,8 GB,128 GB,50MP Rear Camera,17.02 cm (6.7 inch) Display,4500 mAh,"₹27,799",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
2,OnePlus,Nord 2T 5G,Jade Fog,8 GB,128 GB,-,-,4500 mAh,"₹27,995",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
3,OnePlus,Nord 2T 5G,Gray Shadow,8 GB,128 GB,-,-,4500 mAh,"₹27,697",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
4,OnePlus,Nord 2T 5G,Gray Shadow,8 GB,128 GB,-,-,4500 mAh,"₹28,087",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
5,OnePlus,Nord 2T 5G,Gray Shadow,8 GB,128 GB,-,-,4500 mAh,"₹28,050",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
6,OnePlus,Nord CE 2 Lite 5G,Blue Tide,8 GB,128 GB,64MP Rear Camera,16.74 cm (6.59 inch) Display,5000 mAh,"₹21,974",https://www.flipkart.com/oneplus-nord-ce-2-lit...
7,OnePlus,Nord CE 2 Lite 5G,Blue Tide,6 GB,128 GB,64MP Rear Camera,16.74 cm (6.59 inch) Display,5000 mAh,"₹18,400",https://www.flipkart.com/oneplus-nord-ce-2-lit...
8,OnePlus,Nord CE 2 Lite 5G,Black Dusk,6 GB,128 GB,64MP Rear Camera,16.74 cm (6.59 inch) Display,5000 mAh,"₹18,198",https://www.flipkart.com/oneplus-nord-ce-2-lit...
9,OnePlus,Nord CE 5G,Charcoal Ink,8 GB,128 GB,64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh,"₹23,999",https://www.flipkart.com/oneplus-nord-ce-5g-ch...
10,OnePlus,Nord 2 5G,Gray Sierra,12 GB,256 GB,50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh,"₹34,999",https://www.flipkart.com/oneplus-nord-2-5g-gra...
11,OnePlus,Nord 2 5G,Blue Haze,8 GB,128 GB,50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh,"₹29,999",https://www.flipkart.com/oneplus-nord-2-5g-blu...
12,OnePlus,Nord CE 5G,Charcoal Ink,12 GB,256 GB,64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh,"₹28,459",https://www.flipkart.com/oneplus-nord-ce-5g-ch...
13,OnePlus,Nord CE 5G,Charcoal Ink,6 GB,128 GB,64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh,"₹22,990",https://www.flipkart.com/oneplus-nord-ce-5g-ch...
14,OnePlus,Nord 2 5G,Gray Sierra,8 GB,128 GB,50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh,"₹29,999",https://www.flipkart.com/oneplus-nord-2-5g-gra...
15,OnePlus,Nord 2 5G,Blue Haze,12 GB,256 GB,-,-,4500 mAh,"₹33,998",https://www.flipkart.com/oneplus-nord-2-5g-blu...
16,OnePlus,Nord CE 2 Lite 5G,Black Dusk,8 GB,128 GB,64MP Rear Camera,16.74 cm (6.59 inch) Display,5000 mAh,"₹21,990",https://www.flipkart.com/oneplus-nord-ce-2-lit...
17,OnePlus,Nord 2 5G,PAC-MAN,12 GB,256 GB,50MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh,"₹32,990",https://www.flipkart.com/oneplus-nord-2-5g-pac...
18,OnePlus,Nord CE 5G,Blue Void,8 GB,128 GB,64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh,"₹24,990",https://www.flipkart.com/oneplus-nord-ce-5g-bl...
19,OnePlus,Nord 2 5G,Blue Haze,6 GB,128 GB,50MP Rear Camera,16.33 cm (6.43 inch) Display,5G,"₹25,990",https://www.flipkart.com/oneplus-nord-2-5g-blu...
20,OnePlus,Nord 2T 5G,Jade Fog,12 GB,256 GB,-,-,4500 mAh,"₹29,198",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
21,OnePlus,Nord 2T 5G,Gray Shadow,12 GB,256 GB,-,-,4500 mAh,"₹29,198",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
22,OnePlus,Nord 2T 5G,Jade Fog,12 GB,256 GB,-,-,4500 mAh,"₹32,500",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
23,OnePlus,Nord CE 5G,Silver Gray,8 GB,128 GB,64MP Rear Camera,16.33 cm (6.43 inch) Display,4500 mAh,"₹26,999",https://www.flipkart.com/oneplus-nord-ce-5g-si...

# Q5

Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [185]:
maps=webdriver.Chrome()

time.sleep(2)

maps.get("https://www.google.co.in/maps")
maps.maximize_window()
time.sleep(2)

In [206]:
city = input('Enter City name to search : ')
search_city = maps.find_element(By.ID,"searchboxinput")                                                                                   
time.sleep(2)

search_city.send_keys(city)                                                     
search_button = maps.find_element(By.ID,"searchbox-searchbutton").click()                                                             
time.sleep(3)
Location=maps.current_url
coordinates=re.findall(r'@(.*)data',Location)
lat_lon=coordinates[0].split(",")
lat=lat_lon[0]
lon=lat_lon[1]
print("Latitude:",lat,'Longitude:',lon)

Enter City name to search : ludhiana
Latitude: 30.9003191 Longitude: 75.7742709

# Q6

Write a program to scrap all the available details of best gaming laptops from digit.in.

In [208]:
digit=webdriver.Chrome()
time.sleep(2)
digit.get("https://digit.in/")
digit.maximize_window()

In [209]:
digit.find_element(By.XPATH,"/html/body/div[2]/div/ul/li[2]/span").click()
time.sleep(2)
digit.find_element(By.XPATH,"/html/body/div[2]/div/ul/li[2]/div[2]/div/div[1]/span[4]").click()
time.sleep(2)
digit.find_element(By.XPATH,"/html/body/div[2]/div/ul/li[2]/div[2]/div/div[5]/div/div[2]/a/span").click()

In [211]:
product_name=[]
seller=[]
price=[]

product_tag=digit.find_elements(By.XPATH,"//*[@id='summtable']/tbody/tr/td[1]")
for i in product_tag:
    try:
        product_name.append(i.text)
    except NoSuchElementException:
        product_name.append("-")

seller_tag=digit.find_elements(By.CLASS_NAME,"smmerchant")
for i in seller_tag:
    try:
        seller.append(i.text)
    except NoSuchElementException:
        seller.append("-")

price_tag=digit.find_elements(By.CLASS_NAME,"smprice")
for i in price_tag:
    try:
        price.append(i.text)
    except NoSuchElementException:
        price.append("-")

In [212]:
Gaming_laptops=pd.DataFrame({"Product Name":product_name,"Seller":seller,"Price":price})
Gaming_laptops

                  Product Name    Seller      Price
0            HP OMEN 17 (2023)       N/A  ₹ 269,777
1         MSI Titan GT77 12UHS  Flipkart  ₹ 499,990
2         Lenovo Legion 5i Pro    Amazon  ₹ 211,990
3  ASUS ROG Strix Scar 18 2023    Amazon  ₹ 279,990
4  Acer Predator Helios Neo 16    Amazon  ₹ 149,990
5        ASUS ROG Zephyrus G14    Amazon  ₹ 156,990
6                MSI Cyborg 15    Amazon  ₹ 130,990

# Q7

Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [213]:
forbes=webdriver.Chrome()
forbes.get("https://www.forbes.com/")
forbes.maximize_window()

In [219]:
search=forbes.find_element(By.CLASS_NAME,"_69hVhdY4")
search.click()
time.sleep(2)
searchk=forbes.find_element(By.CLASS_NAME,"mpBfVZz3")
searchk.click()
time.sleep(2)
search1=forbes.find_element(By.XPATH,"/html/body/div[1]/header/nav/div[1]/div[1]/div/div[2]/ul/li[2]/div[2]/div[3]/ul/li[1]/a")
search1.click()

In [221]:
table = forbes.find_element(By.XPATH,"//div[@class='TableRow_rowContainer__IC1Tv']")

In [227]:
data=[]
tags=table.find_elements(By.XPATH,'//div[@class="TableRow_cell__db-hv Table_cell__houv9"]')
for i in tags:
    p=i.text
    data.append(p)
Rank=data[0::7]
Name=data[1::7]
Net_worth=data[2::7]
Age=data[3::7]
Citizenship=data[4::7]
Source=data[5::7]
Industry=data[6::7]

In [228]:
Top_billionaires=pd.DataFrame({"Rank":Rank, "Name":Name, "Net worth":Net_worth, "Age":Age, "Citizenship":Citizenship, "Source":Source, "Industry":Industry})
Top_billionaires

,Rank,Name,Net worth,Age,Citizenship,Source,Industry
0,1,Bernard Arnault & family,$211 B,74,France,LVMH,Fashion & Retail
1,2,Elon Musk,$180 B,51,United States,"Tesla, SpaceX",Automotive
2,3,Jeff Bezos,$114 B,59,United States,Amazon,Technology
3,4,Larry Ellison,$107 B,78,United States,Oracle,Technology
4,5,Warren Buffett,$106 B,92,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...,...
195,195,Jin Baofang,$9.6 B,70,China,Solar panels,Energy
196,195,Luo Liguo & family,$9.6 B,67,China,Chemicals,Manufacturing
197,195,Marijke Mars,$9.6 B,58,United States,"Candy, pet food",Food & Beverage
198,195,Pamela Mars,$9.6 B,62,United States,"Candy, pet food",Food & Beverage
199,195,Valerie Mars,$9.6 B,64,United States,"Candy, pet food",Food & Beverage

# Q8

Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video

In [229]:
youtube=webdriver.Chrome()
youtube.get('http://www.youtube.com')
youtube.maximize_window()

In [231]:
Video=youtube.find_element(By.XPATH,"/html/body/ytd-app/div[1]/div/ytd-masthead/div[4]/div[2]/ytd-searchbox/form/div[1]/div[1]/input")
Video.send_keys('spiderverse')
search=youtube.find_element(By.XPATH,"/html/body/ytd-app/div[1]/div/ytd-masthead/div[4]/div[2]/ytd-searchbox/button")
search.click()

In [232]:
vd=youtube.find_element(By.XPATH,"/html/body/ytd-app/div[1]/ytd-page-manager/ytd-search/div[1]/ytd-two-column-search-results-renderer/div/ytd-section-list-renderer/div[2]/ytd-item-section-renderer/div[3]/ytd-video-renderer[1]/div[1]/div/div[1]/div/h3/a/yt-formatted-string")
vd.click()

In [234]:
youtube.execute_script("window.scrollBy(0,500)") 

comment = []
upvote = []
comment_time = []

comment_tag=(youtube.find_elements(By.XPATH,'//yt-formatted-string[@id="content-text"]'))
for i in comment_tag:             
    try:
        comment.append(i.text)
    except NoSuchElementException:
        comment.append("-")

upvote_tag=(youtube.find_elements(By.XPATH,"//*[@id='vote-count-middle']"))
for i in upvote_tag:             
    try:
        upvote.append(i.text)
    except NoSuchElementException:
        upvote.append("-")

comment_time_tag=(youtube.find_elements(By.XPATH,"//*[@id='header-author']/yt-formatted-string/a"))
for i in comment_time_tag:             
    try:
        comment_time.append(i.text)
    except NoSuchElementException:
        comment_time.append("-")

In [235]:
Spiderverse_review=pd.DataFrame({"Comment":comment,"Upvote":upvote,"Comment_ Time":comment_time})
Spiderverse_review

,Comment,Upvote,Comment_ Time
0,WOW! Miles is all grown now. In the first movi...,10K,2 months ago (edited)
1,"It's a truly breathtaking movie, in nearly eve...",5.4K,2 weeks ago (edited)
2,just got out from the cinema and this film has...,4.3K,2 weeks ago
3,You know it’s a good movie when you rewatching...,3.2K,13 days ago
4,"This movie was a masterpiece, even better than...",3.2K,2 weeks ago
5,I’m still not over how incredibly good this mo...,332,7 days ago
6,This movie is going to be great,52K,2 months ago
7,I really didn’t think this movie would surpass...,1.8K,2 weeks ago
8,I just came back from theater and not gonna li...,738,2 weeks ago
9,This was epic seeing in theaters. Otherworldl...,139,13 days ago
10,I just got back from watching it. This is with...,301,2 weeks ago
11,"Okay, after watching the movie, I say: This is...",180,9 days ago
12,Kudos to the animators for making such a huge ...,68K,2 months ago
13,"Having just watched the movie, it was an absol...",283,2 weeks ago
14,The only bad part about this movie was that it...,101,13 days ago
15,Is it wrong for me to say that this movie was ...,36,11 days ago
16,after watching i can say this was one of the g...,134,2 weeks ago
17,I just watched the movie the other and my mind...,15,4 days ago
18,So much in love with the visuals and animation...,4.4K,2 months ago
19,"2:15 ""Nah. Imma do my own thing"" is such a bad...",436,2 weeks ago (edited)

# Q9

Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description

In [286]:
hostelworld=webdriver.Chrome()
hostelworld.get("https://www.hostelworld.com/")
hostelworld.maximize_window()

In [291]:
location=hostelworld.find_element(By.XPATH,"/html/body/div[3]/div/div/div[2]/div[2]/div/div/div[4]/div/div[2]/div/div[1]/div/div/div/input")
location.click()
location=hostelworld.find_element(By.XPATH,"/html/body/div[3]/div/div/div[2]/div[2]/div/div/div[4]/div/div[2]/div/div[1]/div/div/div/input")
location.send_keys('London')

In [293]:
london_select=hostelworld.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div/div/div[4]/div/div[2]/div/div[1]/div/div/ul/li[2]').click()

In [295]:
lets_go_button=hostelworld.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div/div/div[4]/div/div[2]/div/div[6]/button').click()

In [278]:
len(Hostel_Name),len(distance),len(overall_review),len(facilities),len(price )

(31, 30, 31, 0, 0)

In [307]:
# Hostel name
Hostel_Name = []
names = hostelworld.find_elements(By.XPATH,'//h2[@class="title title-6"]')
for i in names:
    Hostel_Name.append(i.text)
time.sleep(2)

# Distance from city
distance = []
distances = hostelworld.find_elements(By.XPATH,'//span[@class="description"]')
for i in distances:
    distance.append(i.text)
time.sleep(2)

#Review    
overall_review = []
review = hostelworld.find_elements(By.XPATH,'//div[@class="keyword"]')
for i in review:
    overall_review.append(i.text)
time.sleep(2)
#Rating
rating=[]
r= hostelworld.find_elements(By.XPATH,'//div[@class="keyword"]')
for i in r:
    rating.append(i.text)
time.sleep(2)

In [281]:
h_urls=[]
url=hostelworld.find_elements(By.XPATH,'//a[@class="property-card-container horizontal"]')
for i in url:
    h_urls.append(i.get_attribute('href'))
len(h_urls)

30

In [283]:
property_description=[]
for i in h_urls:
    hostelworld.get(i)
    time.sleep(1)
    try:
        p_d=hostelworld.find_element(By.XPATH,'//div[@class="content collapse-content"]')
        property_description.append(p_d.text)
    except NoSuchElementException as e:
        property_description.append('-')

In [296]:
facilities=[]
total_reviews=[]
for i in h_urls:
    hostelworld.get(i)
    time.sleep(1)
    try:
        f=hostelworld.find_element(By.XPATH,'//ul[@class="facilities"]')
        facilities.append(f.text)
    except NoSuchElementException as e:
        facilities.append('-')
         
    try:
        tr=hostelworld.find_element(By.XPATH,'//div[@class="reviews"]')
        total_reviews.append(tr.text)
    except NoSuchElementException as e:
        total_reviews.append('-')

In [308]:
len(Hostel_Name),len(distance),len(rating),len(total_reviews),len(overall_review),len(facilities),len(property_description)

(30, 30, 31, 30, 31, 30, 30)

In [309]:
Hostel=pd.DataFrame({"Hostel Name":Hostel_Name,"Distance from City Centre":distance,"Ratings":rating[1:],"Total Reviews":total_reviews,"Overall Review":overall_review[1:],"Facilities":facilities,"Property Description":property_description})
Hostel

,Hostel Name,Distance from City Centre,Ratings,Total Reviews,Overall Review,Facilities,Property Description
0,Onefam Notting Hill by Hostel One,Hostel - 5.5km from city centre,Superb,2057 Total Reviews,Superb,Linen Included Free WiFi Free Internet Access,The perfect place for solo travelers to connec...
1,St Christopher's Village,Hostel - 1.8km from city centre,Very Good,12151 Total Reviews,Very Good,Linen Included Free WiFi Free Internet Access,St Christopher's Inn at The Village in London ...
2,Urbany Hostel London,Hostel - 5.4km from city centre,Superb,778 Total Reviews,Superb,Linen Included Free WiFi,"Welcome to Urbany Hostel London, our first int..."
3,NX London Hostel,Hostel - 6.1km from city centre,Fabulous,1884 Total Reviews,Fabulous,Free Breakfast Linen Included Towels Included ...,Welcome to NX London Hostel!\n\nPLEASE READ IN...
4,Safestay London Elephant & Castle,Hostel - 1.7km from city centre,Very Good,4953 Total Reviews,Very Good,Linen Included Free WiFi,Safestay at Elephant & Castle is ideal if you ...
5,Phoenix Hostel,Hostel - 4.2km from city centre,Very Good,4126 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi Free I...,"The Phoenix Bar & Hostel, housed in a homely E..."
6,No.8 Willesden Hostel London,Hostel - 10km from city centre,Good,5013 Total Reviews,Good,Linen Included Free WiFi,At No.8 we take pride in our Customer Service ...
7,Safestay London Kensington Holland Park,Hostel - 5.8km from city centre,Very Good,1528 Total Reviews,Very Good,Linen Included Free WiFi,Safestay Holland Park\n\nSafestay Holland Park...
8,No.8 Seven Sisters,Hostel - 9km from city centre,Rating,4010 Total Reviews,Rating,Linen Included Free WiFi,"For Great Facilities, Comfort & Affordability ..."
9,London Backpackers,Hostel - 11.9km from city centre,Very Good,4468 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi Free I...,IMPORTANT NOTICE: \n\nThis hostel is for 18 - ...
10,Queen Elizabeth Chelsea,Hostel - 5.7km from city centre,Very Good,3480 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi Free I...,PLEASE NOTE WE ONLY ACCEPT GUESTS FROM THE AGE...
11,St Christopher's Hammersmith,Hostel - 7.5km from city centre,Very Good,4243 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi Free I...,"Good hostel, in a very convenient location new..."
12,St Christopher's Camden,Hostel - 4.3km from city centre,Very Good,4035 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi Free I...,"Find our Camden hostel in London's north, smac..."
13,International Students House,Hostel - 3.3km from city centre,Superb,1035 Total Reviews,Superb,Linen Included Free City Maps Towels Included ...,International Students House provides affordab...
14,"PubLove @ The Steam Engine, Waterloo",Hostel - 0.5km from city centre,Fabulous,394 Total Reviews,Fabulous,Linen Included Free City Maps Free WiFi,The heart & soul of London backpacking\nPull u...
15,St Christopher's Greenwich,Hostel - 7.6km from city centre,Very Good,3349 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi Free I...,Discover South London's rich history in the ci...
16,Saint James Backpackers,Hostel - 5.5km from city centre,Very Good,1883 Total Reviews,Very Good,Free Breakfast Linen Included Free City Maps F...,We are located in central London - just 5 minu...
17,Selina Camden,Hostel - 5.5km from city centre,Fabulous,50 Total Reviews,Fabulous,Linen Included Towels Included Free WiFi,"Among underground music venues, innovative mus..."
18,St Christopher's Shepherds Bush,Hostel - 7km from city centre,Very Good,772 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi,St Christopher's Inn Shepherds Bush gives trav...
19,Kensal Green Backpackers,Hostel - 8.2km from city centre,Rating,3710 Total Reviews,Rating,Linen Included Free City Maps,Kensal Green Backpackers is a legendary hostel...
20,"PubLove @ The Crown, Battersea",Hostel - 4.7km from city centre,Very Good,301 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi,Do London like a local.\nStay just outside the...
21,Book a Bed Hostels,Hostel - 6.9km from city centre,Very Good,1255 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi Free I...,Welcome to Venture Hostel.Venture Hostel is a ...
22,"PubLove @ The White Ferry, Victoria",Hostel - 2.4km from city centre,Very Good,337 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi,"Walk to the river, turn left, and just keep wa..."
23,Hostelle London,Hostel - 5.1km from city centre,Fabulous,11 Total Reviews,Fabulous,Linen Included Free City Maps Free WiFi Free I...,Hostelle is the first and only all-female host...
24,Hootananny Hostel,Hostel - 5km from city centre,Very Good,1511 Total Reviews,Very Good,Free Breakfast Linen Included Free City Maps F...,Hootananny is a lively hostel with spacious ro...
25,PubLove @ The Rose & Crown,Hostel - 1.6km from city centre,Very Good,189 Total Reviews,Very Good,Linen Included Free City Maps Free WiFi,"Food & culture lovers, assemble!\nThe Rose & C..."
26,Elmwood Hotel,Hotel - 3.2km from city centre,Very Good,128 Total Reviews,Very Good,Free Internet Access,Great location and extremely clean. Rooms tiny...
27,Tony's House Hotel,Hotel - 4.3km from city centre,Fabulous,422 Total Reviews,Fabulous,Free Breakfast Free Internet Access,Central London Hotel Accommodation situated in...
28,"PubLove @ The Exmouth Arms, Euston",Hostel - 3.4km from city centre,Good,1078 Total Reviews,Good,Linen Included Free City Maps Free WiFi,Do Camden by day and curb side beers by night....
29,London Waterloo Hostel,Hostel - 0.7km from city centre,Rating,2534 Total Reviews,Rating,Linen Included Free City Maps Free WiFi Free I...,We have the honor of being the closest dedicat...